packages:
  - "apps/services/*"
  - "apps/workers/*"
  - "packages/*"
  - "packages/shared/*"

allowBuilds:
  "@nestjs/core": true
  argon2: true
  esbuild: true
  protobufjs: true

catalog:
  typeorm: "0.3.30"
  kafkajs: "2.2.4"
